spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false


mybatis:
  typeAliasesPackage: com.wry.security.pojo
  mapper-locations: classpath:mapperxml/*.xml
server:
  port: 8099



